# Generated by Django 4.1.2 on 2022-12-28 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snowflake_drf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualtargetformmetricvalue',
            name='configuration_form_mtpm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snowflake_drf.configurationformmtpm'),
        ),
    ]
