# Generated by Django 4.1.2 on 2022-12-28 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snowflake_drf', '0003_backing_up_annual_target_form_metric_id_to_configuration_form_mtpm_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualtargetformmetricvalue',
            name='annual_target_form_metrics',
        ),
        migrations.AlterField(
            model_name='annualtargetformmetricvalue',
            name='configuration_form_mtpm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snowflake_drf.configurationformmtpm'),
        ),
        migrations.DeleteModel(
            name='AnnualTargetFormMetric',
        ),
    ]
