# Generated by Django 4.1.2 on 2022-12-30 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snowflake_drf', '0004_remove_annualtargetformmetricvalue_annual_target_form_metrics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualtargetformmetricvalue',
            old_name='annual_target_form_metric_values_id',
            new_name='annual_target_form_metric_value_id',
        ),
    ]
