# Generated by Django 4.1.2 on 2023-03-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowflake_drf', '0006_technology_technology_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfinancialformmetric',
            name='pi_atribute_name',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='monthlyfinancialformmetric',
            name='save_to_pi',
            field=models.SmallIntegerField(default=0),
        ),
    ]
