# Generated by Django 4.1.2 on 2023-03-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snowflake_drf', '0007_monthlyfinancialformmetric_pi_atribute_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyfinancialformmetric',
            old_name='pi_atribute_name',
            new_name='pi_attribute_name',
        ),
    ]
