# Generated by Django 4.1.2 on 2023-03-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowflake_drf', '0008_rename_pi_atribute_name_monthlyfinancialformmetric_pi_attribute_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationformleadingindicator',
            name='configuration_form_leading_indicator_external_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='configurationformmtpm',
            name='configuration_form_mtpm_external_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='technology',
            name='technology_external_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
