# Generated by Django 4.1.2 on 2023-03-28 13:15

from django.db import migrations, models, transaction

model_name = 'monthlyfinancialformmetric'
mapping = (
    ('Grind', '0-Production'),
    ('Yield', '1-Yield'),
    ('Financial', '2-Product Value'),
    ('NR Financial', '3-Natural Resource Cost')
)


def populate(apps, schema_editor):
    Model = apps.get_model('snowflake_drf', model_name)
    _mapping = dict(mapping)
    with transaction.atomic():
        for row in Model.objects.all():
            row.category = _mapping.get(row.category, row.category)
            row.save()


def backwards(apps, schema_editor):
    Model = apps.get_model('snowflake_drf', model_name)
    _mapping = dict((pair[1], pair[0]) for pair in mapping)
    with transaction.atomic():
        for row in Model.objects.all():
            row.category = _mapping.get(row.category, row.category)
            row.save()
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('snowflake_drf', '0010_monthlyfinancialformmetric_category_and_more'),
    ]

    operations = [
        migrations.RunPython(populate, backwards),
    ]
