# Generated by Django 4.2.1 on 2023-07-12 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("snowflake_drf", "0011_monthlyfinancialformmetric_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configurationformmtpm",
            name="technology",
        ),
        migrations.AddField(
            model_name="configurationformmtpm",
            name="plant_technology",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="snowflake_drf.planttechnology",
            ),
        ),
    ]
