# Generated by Django 4.2.1 on 2023-07-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowflake_drf", "0012_remove_configurationformmtpm_technology_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationformleadingindicator",
            name="element_path",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="configurationformmtpm",
            name="element_path",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
