# Generated by Django 4.2.3 on 2023-09-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "snowflake_drf",
            "0013_configurationformleadingindicator_element_path_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyfinancialformmetric",
            name="subcategory",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="monthlyfinancialformmetricvalue",
            name="metric_value_string",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="monthlyfinancialformmetric",
            name="uom_imperial",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="monthlyfinancialformmetric",
            name="uom_metric",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="monthlyfinancialformmetricvalue",
            name="metric_value",
            field=models.FloatField(null=True),
        ),
    ]
