# Generated by Django 4.2.1 on 2023-09-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowflake_drf", "0014_monthlyfinancialformmetric_subcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyfinancialformmetric",
            name="is_numeric",
            field=models.BooleanField(default=False),
        ),
    ]
