# Generated by Django 4.2.6 on 2023-10-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowflake_drf", "0017_agent_datatransfer_dataviews_sequentialdata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowflakeLogging",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=50, null=True)),
                ("message", models.CharField(max_length=100, null=True)),
                ("event", models.CharField(max_length=50, null=True)),
                ("log_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "snowflake_logging",},
        ),
    ]
